### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by jorgemmsilva** [tvainika/objection-keyset-pagination#1]
Cool lib, I think the concept is good, unfortunately it doesn't seem to work :/

Tried using this on a small project, using a simple query:
```
await ModeNamel.query()
    .limit(N)
    .keysetPage()
```
but `result.keyset` is always equal to: `{ first: {}, last: {} }`

**Comment by tvainika** [comment]
Keyset pagination works based on `ORDER BY` clauses in your query. You must have at least one `.orderBy(some column)`  with your query. I've added now a check for that.
