### ISSUE TITLE
How can i navigate to the next page

### ISSUE THREAD

**Issue by marufmax** [tvainika/objection-keyset-pagination#3]
Hi,
This is not an issue, a noob question! 
Thanks for the this package. I want to show pagination with vuejs with express backend. 
I am getting
```
"paginate": {
"first": 1,
"last": 10
}
```
this object. How can i navigate to the next page? 

Can i get a response something like that? 
```
   "current_page": 1,
    "last_page": 3,
    "next_page_url": "/api/animals?page=2",
    "prev_page_url": null,
```

**Comment by tvainika** [comment]
Did you take a look of example code at https://github.com/tvainika/objection-keyset-pagination/tree/master/examples/vuejs-keyset-scrolling ?
